#!/bin/sh -E

WORKDIR=$1

if ! [ -d "angie/" ]; then
    echo "Get angie v2.8.1 with patch"
    git clone git@github.com:webserver-llc/angie.git $WORKDIR/angie
    cd $WORKDIR/angie
    git checkout tags/Angie-1.8.2
    git apply $WORKDIR/patches/angie.patch
fi

if ! [ -d "openssl/" ]; then
    echo "Get openssl v3.4.1 with patch"
    git clone git@github.com:openssl/openssl.git $WORKDIR/openssl
    cd $WORKDIR/openssl
    git checkout tags/openssl-3.4.1 
    git apply $WORKDIR/patches/openssl.patch
fi

if ! [ -d "angie-module-lua/" ]; then
    echo "Get packages for angie-module-lua"
    mkdir $WORKDIR/angie-module-lua
    cd $WORKDIR/angie-module-lua
    wget https://github.com/openresty/luajit2/archive/refs/tags/v2.1-20250117.zip && unzip v2.1-20250117.zip && rm v2.1-20250117.zip 
    wget https://github.com/vision5/ngx_devel_kit/archive/refs/tags/v0.3.4.zip && unzip v0.3.4.zip && rm v0.3.4.zip 
    wget https://github.com/openresty/lua-nginx-module/archive/refs/tags/v0.10.28.zip && unzip v0.10.28.zip && rm v0.10.28.zip 
    wget https://github.com/openresty/lua-resty-core/archive/refs/tags/v0.1.31.zip && unzip v0.1.31.zip && rm v0.1.31.zip 
    wget https://github.com/openresty/lua-resty-lrucache/archive/refs/tags/v0.15.zip && unzip v0.15.zip && rm v0.15.zip
fi

echo "Return to working directory"
cd $WORKDIR