#!/bin/sh -E

WORKDIR=$1
PREFIX=$WORKDIR/$2

# install luajit2 (necessary for angie-module-lua)
export LUAJIT_LIB=/usr/local/lib/ && export LUAJIT_INC=/usr/local/include/luajit-2.1/
cd $WORKDIR/angie-module-lua/luajit2-2.1-20250117/
make -j && sudo make install

# make binary
cd $WORKDIR/angie
#./configure --with-debug --with-compat --add-module=../src --with-http_ssl_module --with-openssl=../openssl --prefix=$(pwd)/../angie_local
./configure --with-compat --prefix=$PREFIX \
    --with-http_ssl_module --with-openssl=../openssl \
    --add-module=../src \
    --add-module=../angie-module-lua/ngx_devel_kit-0.3.4 --with-ld-opt="-Wl,-rpath,/usr/local/lib" \
    --add-module=../angie-module-lua/lua-nginx-module-0.10.28
make -j
make install

# install lua-resty-* (necessary for angie-module-lua)
cd $WORKDIR/angie-module-lua/lua-resty-core-0.1.31
sudo make install PREFIX=$PREFIX
cd $WORKDIR/angie-module-lua/lua-resty-lrucache-0.15
sudo make install PREFIX=$PREFIX

cd $WORKDIR
