#!/bin/sh -e

mkdir angie-module-lua
cd angie-module-lua
wget https://github.com/openresty/luajit2/archive/refs/tags/v2.1-20250117.zip && unzip v2.1-20250117.zip && rm v2.1-20250117.zip 
wget https://github.com/vision5/ngx_devel_kit/archive/refs/tags/v0.3.4.zip && unzip v0.3.4.zip && rm v0.3.4.zip 
wget https://github.com/openresty/lua-nginx-module/archive/refs/tags/v0.10.28.zip && unzip v0.10.28.zip && rm v0.10.28.zip 
wget https://github.com/openresty/lua-resty-core/archive/refs/tags/v0.1.31.zip && unzip v0.1.31.zip && rm v0.1.31.zip 
wget https://github.com/openresty/lua-resty-lrucache/archive/refs/tags/v0.15.zip && unzip v0.15.zip && rm v0.15.zip
wget https://github.com/openresty/stream-lua-nginx-module/archive/refs/tags/v0.0.16.zip && unzip v0.0.16.zip && rm v0.0.16.zip
