#!/bin/sh -e

OPENSSL_VERSION=$1

wget https://github.com/openssl/openssl/releases/download/openssl-$OPENSSL_VERSION/openssl-$OPENSSL_VERSION.tar.gz
tar -xvf openssl-$OPENSSL_VERSION.tar.gz
rm openssl-$OPENSSL_VERSION.tar.gz
cd openssl-$OPENSSL_VERSION
patch -p1 < ../patches/openssl-$OPENSSL_VERSION.patch
